name: Build LaTeX document

on: [pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install MS-Core-Fonts
        run: sudo apt-get update && ttf-mscorefonts-installer

      - name: Update font cache
        run: fc-cache -fv

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true