name: Build LaTeX document

on: [pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install Liberation Sans font
        run: sudo apt-get update && sudo apt-get install -y fonts-liberation

      - name: Update font cache
        run: fc-cache -fv

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: |
            /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf
            /usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf
            /usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf
            /usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf
